// AUTO-GENERATED partly from public/gallery/. See scripts/generate-gallery.js
// to regenerate after adding new photos.

export type GalleryImage = {
  src: string;
  alt: string;
  width: number;
  height: number;
};

export const GALLERY: GalleryImage[] = [
  { src: "/gallery/20250411_172500.jpg", alt: "Paver-edged mailbox bed filled with white gravel in a West Michigan residential neighborhood", width: 4000, height: 3000 },
  { src: "/gallery/20250411_172601.jpg", alt: "Oval paver-edged front yard bed with white rock, ornamental tree, and boulder accent beside a white house", width: 4000, height: 3000 },
  { src: "/gallery/20250411_172615.jpg", alt: "Curved paver-edged landscape bed with white gravel, a young tree, boulder accent, and shrubs along a house", width: 4000, height: 3000 },
  { src: "/gallery/20250411_172838.jpg", alt: "Paver-edged landscape bed with white gravel, dormant shrubs, and decorative pots along the front of a house", width: 4000, height: 3000 },
  { src: "/gallery/20250411_172928.jpg", alt: "Circular paver-edged tree ring filled with white gravel and a boulder accent around a young tree in a front yard", width: 4000, height: 3000 },
  { src: "/gallery/FB_IMG_1749655041513.jpg", alt: "Deep excavated trench with skid-steer during a residential yard drain installation", width: 1080, height: 1920 },
  { src: "/gallery/FB_IMG_1754343308690.jpg", alt: "Low paver-capped retaining wall along the side of a brick house with gravel drainage channel, mulch bed, and newly seeded lawn", width: 1440, height: 1440 },
  { src: "/gallery/FB_IMG_1754343316006.jpg", alt: "Block retaining wall with gravel drainage channel between the wall and a brick house foundation with gas meter visible", width: 1440, height: 1440 },
  { src: "/gallery/FB_IMG_1758729997354.jpg", alt: "Fresh sod installed in a backyard with horizontal-board wood fence and deck", width: 1440, height: 1440 },
  { src: "/gallery/FB_IMG_1758730003165.jpg", alt: "Freshly installed sod in a side yard with a horizontal cedar fence with black metal posts and a wood deck", width: 1440, height: 1440 },
  { src: "/gallery/FB_IMG_1758730009531.jpg", alt: "Wide backyard with freshly laid sod, horizontal cedar fence, mature trees, and a decorative yard ornament", width: 1440, height: 1440 },
  { src: "/gallery/FB_IMG_1771690358929.jpg", alt: "Gray block retaining wall with integrated stone steps climbing a hillside next to a house with newly seeded lawn", width: 1440, height: 1440 },
  { src: "/gallery/FB_IMG_1771690390552.jpg", alt: "Natural stone retaining wall with gravel base on a graded lot next to a green building with wooded backdrop", width: 1440, height: 1440 },
  { src: "/gallery/FB_IMG_1771690408247.jpg", alt: "Gray block retaining wall with paver steps and planting beds along a chain-link fence in a front yard", width: 1440, height: 1440 },
  { src: "/gallery/FB_IMG_1771944411767.jpg", alt: "Tall curved brown block retaining wall with plantings on the upper tier, green lawn below, and a white shed above", width: 1440, height: 1440 },
  { src: "/gallery/FB_IMG_1779146552127.jpg", alt: "Long block staircase with retaining walls climbing a wooded hillside, curved wall with white gravel and drain grate", width: 1440, height: 1440 },
  { src: "/gallery/FB_IMG_1779146559581.jpg", alt: "Fan-shaped paver landing at the base of block steps with retaining walls, black metal railing above, and boulders", width: 1440, height: 1440 },
  { src: "/gallery/FB_IMG_1771690122929.jpg", alt: "Raised concrete pad on a block retaining wall behind a house with crew workers and green lawn in foreground", width: 1440, height: 1080 },
  { src: "/gallery/FB_IMG_1743118546502.jpg", alt: "Curved block retaining wall with gravel fill creating a raised bed area next to a blue house and a storage shed", width: 960, height: 1290 },
  { src: "/gallery/FB_IMG_1743118573385.jpg", alt: "Tumbled block retaining wall with stone steps beside a garage and a wooden privacy fence in background", width: 960, height: 1290 },
  { src: "/gallery/FB_IMG_1743117831187.jpg", alt: "Two-tier block retaining wall with gravel-filled built-in planter next to a concrete sidewalk in autumn", width: 960, height: 1280 },
  { src: "/gallery/FB_IMG_1743117833712.jpg", alt: "Two-tier block retaining wall with gravel planter and block steps leading up to the porch of a house", width: 960, height: 1280 },
  { src: "/gallery/FB_IMG_1743117600110.jpg", alt: "Gravel stepping-stone path through a lush shade garden with hostas, ferns, river rock, and mature trees", width: 960, height: 1200 },
  { src: "/gallery/FB_IMG_1743117627617.jpg", alt: "Curved multi-tier retaining wall with river rock edging and graded soil, houses on a green hillside behind", width: 960, height: 1200 },
  { src: "/gallery/FB_IMG_1743117921629.jpg", alt: "Block retaining wall headwall around a culvert pipe with river rock riprap over a stream and straw erosion blanket", width: 960, height: 1200 },
  { src: "/gallery/FB_IMG_1742200746321.jpg", alt: "Front entry mulch beds with daffodils, planters, and a concrete walkway along a brick-front home", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1742200776590.jpg", alt: "Curved front yard bed with dark mulch, ornamental shrubs, yellow spireas, a Japanese maple, and decorative boulders", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743097713578.jpg", alt: "Tall multi-colored block retaining wall with stone steps and river rock on a hillside", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743097721306.jpg", alt: "Curved natural stone retaining wall along a lakefront with prepared planting bed on top", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743097735372.jpg", alt: "Long brown-toned block retaining wall with river rock ground cover behind a house with a raised deck", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117122277.jpg", alt: "Low paver-capped retaining wall along the side of a brick house with gravel, mulch beds, and a white privacy fence", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117134166.jpg", alt: "Stacked sod rolls beside fresh mulch and a newly laid green lawn with a redbud tree and brown building in the background", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117145372.jpg", alt: "Large green lawn bordered by pine trees, a curved stone retaining wall, and a brown home with a red patio umbrella", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117152392.jpg", alt: "Lush green lawn with curved edging, a redbud tree, a river rock drainage area near a driveway, and pine trees", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117164477.jpg", alt: "Two crew members operating a Vermeer wood chipper on a residential lot, feeding branches while chips shoot into a dump truck", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117175401.jpg", alt: "Aerial view of a Bernal tree-removal job with cut log sections, crew trailer, trucks, and chipper", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117191659.jpg", alt: "Fresh cedar mulch beds around trees at a brick house with a concrete sidewalk, Bernal branded trailer in the driveway, and a worker with a leaf blower", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117209608.jpg", alt: "Front yard landscape bed with wood chip mulch, flowering shrubs, evergreens, and curved edging at a white house", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117233033.jpg", alt: "Low gray block retaining wall with cap stones along a driveway with a new cedar privacy fence and gate on top", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117239145.jpg", alt: "New cedar privacy fence sections along a property line with a weathered wood deck behind and bare dirt in the foreground", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117247736.jpg", alt: "Gray block retaining wall with integrated steps and herringbone paver landing at the base next to a house", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117257155.jpg", alt: "View looking down gray block steps alongside a retaining wall with paver landing visible below", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117261563.jpg", alt: "Raised herringbone-pattern paver landing with block steps leading up next to an AC unit and house siding", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117264881.jpg", alt: "Raised paver landing with herringbone pattern, block steps, and retaining wall next to a sliding glass door", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117268557.jpg", alt: "Corner retaining wall planter bed with wood chip mulch, trees, ornamental grasses, and flowers in front of a stone-accented home", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117334950.jpg", alt: "Large rectangular paver patio with a square block fire pit in the center in a rural backyard", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117341843.jpg", alt: "Gray block retaining wall with stepping caps and integrated steps alongside a newly seeded lawn with straw", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117351300.jpg", alt: "Red and charcoal paver walkway through gravel beds scattered with autumn leaves", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117357646.jpg", alt: "Red and charcoal paver stepping stones set in pea gravel through a landscape bed", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117364709.jpg", alt: "Terraced front yard with red-and-charcoal paver stepping stones in gravel bordered by brown block retaining wall tiers", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117367845.jpg", alt: "Curved walkway of red-and-charcoal paver stepping stones through a gravel yard with brown block borders, white vinyl fence, and mature trees", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117404071.jpg", alt: "Multi-tier curved block retaining wall with integrated steps on a wooded hillside with freshly graded soil and paver driveway below", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117407130.jpg", alt: "Large curved two-tier block retaining wall with gray caps on a wooded lot with drain pipe visible and bare soil grading in progress", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117410471.jpg", alt: "Long block retaining wall with integrated steps running along a hillside next to a house with white vinyl and chain-link fences", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117427847.jpg", alt: "Kidney-shaped block retaining wall planter bed with dark mulch around a tree in a green lawn with a white house behind", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117430602.jpg", alt: "Large circular block retaining wall planter bed with dark mulch in a backyard with a pergola-covered deck and house behind", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117448603.jpg", alt: "Freshly poured concrete pad next to a red house with a natural stone retaining wall and wooded hillside", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117455681.jpg", alt: "Fresh smooth-finished concrete driveway alongside a red-sided house on a wooded lot", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117459162.jpg", alt: "New concrete driveway and pad wrapping around a red house with open garage and old cracked asphalt at the edge", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117469610.jpg", alt: "Massive natural stone retaining wall with stone slab steps built from rough-cut limestone blocks on a wooded hillside", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117472398.jpg", alt: "Natural stone staircase with rough-cut limestone steps and retaining walls flanking both sides looking uphill through trees", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117476133.jpg", alt: "Natural stone steps with retaining wall curving at a landing with crushed stone base and graded hillside behind", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117488560.jpg", alt: "West Michigan project by Bernal Landscape Management", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117491703.jpg", alt: "Freshly poured concrete pad enclosed by a block retaining wall on three sides with a wooded backdrop at dusk", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117524118.jpg", alt: "Two-tier tan block retaining wall with integrated steps on a sloped backyard with AC unit and green lawn", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117529330.jpg", alt: "Project by Bernal Landscape Management in West Michigan", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117532395.jpg", alt: "Completed residential work by Bernal Landscape", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117535641.jpg", alt: "Low block retaining wall planter bed with boxwood shrubs and a young tree next to a house foundation with straw-covered seed", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117555124.jpg", alt: "Freshly laid sod on a side yard slope with white gravel drainage bed alongside and mature trees in a residential neighborhood", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117562825.jpg", alt: "Pea gravel drainage strip framed by river rock alongside a freshly sodded lawn", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117569528.jpg", alt: "Bernal Landscape crew installing sod on a front lawn with pink utility flags and company work truck on the street", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117587193.jpg", alt: "Block retaining wall under a raised deck with large boulders and wood chip mulch transitioning to the adjacent yard", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117591531.jpg", alt: "Tall stepped block retaining wall under a raised deck with a boulder accent viewed from the concrete pad below", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117607660.jpg", alt: "Concrete pool deck and in-ground pool shell with a dark block retaining wall behind a blue house on a graded hillside", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117612267.jpg", alt: "Wide view of concrete pool deck with a covered hot tub, in-ground pool, dark block retaining wall, and a gray storage shed", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117615939.jpg", alt: "Concrete block retaining wall under construction with rebar grid and gravel base next to an existing concrete pad and hot tub", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117644259.jpg", alt: "Long stepped gray block retaining wall running along the side of a house on a sloped lawn with a red Japanese maple tree", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117657475.jpg", alt: "Block retaining wall with stone slab steps curving down a wooded hillside with snow on the ground and bare trees", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117671590.jpg", alt: "Paver block staircase climbing through mulched beds with boulders and black-eyed Susan flowers", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117674708.jpg", alt: "Paver stairs with flagstone landing through mulched beds, boulders, and a Bernal yard sign", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117684384.jpg", alt: "Paver staircase with retaining wall, river rock, and ornamental grass ascending a hillside", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117687157.jpg", alt: "Tall block retaining wall with gravel drainage and river rock at base, ornamental grasses on top tier, under a raised deck", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117691461.jpg", alt: "Block retaining wall with integrated paver steps leading up a gravel-covered hillside with river rock and mature trees", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117694080.jpg", alt: "Long brown block retaining wall with river rock and ornamental grasses behind a blue house with a raised deck", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117734461.jpg", alt: "Gray marbled block retaining wall with black chain-link fence on top in a residential neighborhood with gravel base", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117739068.jpg", alt: "Backyard with white gravel pad bordered by red brick edging surrounded by dark mulch beds and new seeded lawn", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117742747.jpg", alt: "Side yard with dark mulch bed along a gray block retaining wall and chain-link fence with white gravel pad visible behind", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117751795.jpg", alt: "Block retaining wall with integrated gray cap steps leading up to a backyard with a privacy fence and fall foliage", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117754189.jpg", alt: "Raised in-ground pool with block retaining wall surround, concrete deck, paver steps, and black metal safety fence in a wooded backyard", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117756556.jpg", alt: "In-ground pool with blue cover surrounded by black metal fence on bare graded soil in a wooded backyard with privacy fence", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117758790.jpg", alt: "Curved block retaining wall with paver cap steps leading up to an in-ground pool with blue cover and volleyball net on a wooded lot", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117761135.jpg", alt: "Large kidney-shaped in-ground pool with concrete deck, basketball hoop, volleyball net, and block retaining wall with paver steps in a wooded backyard", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117779061.jpg", alt: "New concrete pad poured next to a garage with block edging on a green lawn surrounded by trees", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117781054.jpg", alt: "Wide concrete pad alongside a house with vinyl siding and a car parked in the driveway on a wooded lot", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117796508.jpg", alt: "Lakefront paver patio with block retaining wall, built-in fire pit, and river rock border on a sandy beach with houses across the water", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117799442.jpg", alt: "Lakefront paver patio with fire pit, river rock border, block retaining wall, and kayak storage viewed from the water with homes across the lake", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117801877.jpg", alt: "Large terraced gray block retaining wall with integrated steps and river rock drainage channel in a backyard with a trampoline and above-ground pool", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117813825.jpg", alt: "Long gray block retaining wall with paver cap and river rock bed running alongside an above-ground pool with a white privacy fence behind", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117816491.jpg", alt: "Backyard with terraced gray block retaining walls, integrated block steps, string lights, white gravel beds, above-ground pool, and a terracotta planter on the deck", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117819596.jpg", alt: "Backyard with multi-tier gray block retaining wall, integrated steps, sandbox with a slide, and a trampoline on the upper level behind a lawn", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117822851.jpg", alt: "Raised multi-color paver patio with block retaining wall edge behind a house with sliding glass doors, a grill, and gravel beds with landscape lighting", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117836894.jpg", alt: "Multi-color paver patio surface with an L-shaped dark block seat wall and lush green plantings in the background", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117839231.jpg", alt: "Two-tier raised paver patio with dark block retaining walls and steps behind a white house with a wood privacy fence and straw-covered new seed", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117847310.jpg", alt: "Raised gray block paver patio with integrated steps and block planters viewed from the backyard of a two-story white house with straw-covered seed", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117850145.jpg", alt: "Front of a ranch-style house with a new gray herringbone paver walkway and block step landing leading to the front door with fresh straw-covered seed", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117852791.jpg", alt: "Two-tier raised gray block paver patio with wide steps and block planters behind a two-story house with sliding glass doors and straw-covered seed", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117855184.jpg", alt: "Front of a gray ranch house with a new gray herringbone paver walkway extending from the driveway to the front door with fresh straw-covered seed", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117857841.jpg", alt: "Raised gray block paver patio with wide steps and block column planters behind a two-story white house with sliding glass doors and straw-covered seed on the lawn", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117860873.jpg", alt: "Front of a ranch house with white shutters, new gray block raised planter bed with dark soil, block steps to the front door, and a paver walkway to the driveway", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117864108.jpg", alt: "Close-up of a front entry with gray herringbone paver walkway, dark block steps with block column pillars leading to a brown front door, and straw-covered seed", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117866951.jpg", alt: "Large herringbone paver patio behind a white house with two sets of sliding glass doors and two dark block step landings with block column pillars", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117869972.jpg", alt: "Modern backyard with large-format gray paver patio featuring a geometric inlay pattern, dark block retaining walls, gravel beds, a gold statue on a pedestal, and block steps", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117872335.jpg", alt: "Checkerboard stepping stone walkway with alternating light and dark large-format pavers and river rock between, set in a dark gravel bed along a modern white house", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117878097.jpg", alt: "Checkerboard stepping stone walkway leading along a modern house toward a large paver patio with a block fire pit, dark gravel beds, river rock accents, and ornamental plantings", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117880340.jpg", alt: "Front of a modern white and black farmhouse-style home with dark block retaining wall, planter beds with dark gravel and an ornamental tree, block steps, and a concrete driveway", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117882756.jpg", alt: "Elevated view of dark block retaining walls with gravel beds, a dark paver patio with geometric light-color inlay, a gold statue on a block pedestal, and block steps beside a white house", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117885194.jpg", alt: "Large-format paver stepping stones with river rock between in a gravel bed, dark block retaining wall with integrated steps, sunken paver patio area, and a gold statue beside a modern house", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117888928.jpg", alt: "Dark block retaining walls on both sides of a sunken area with integrated block steps and light cap stones, gravel bed alongside a white house with an AC unit", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117891962.jpg", alt: "Side yard with dark block retaining walls, integrated block steps with light cap stones, gravel bed, paver patio below, and trimmed shrubs on the wall cap", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117895242.jpg", alt: "Large modern white and black farmhouse-style home at dusk with fresh green lawn, dark block planter beds with gravel and ornamental trees, and a concrete driveway", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117897840.jpg", alt: "Expansive dark herringbone paver patio behind a modern two-story white house with a second-story balcony, wood-post covered area, and block retaining wall with gravel bed", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117903220.jpg", alt: "Side of a modern white house with dark block retaining wall, integrated steps, gravel bed, paver patio, trimmed shrubs, and an AC unit with subdivision homes behind", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117906899.jpg", alt: "Long white vinyl privacy fence running along a residential property line with a utility pole and old stone edging at the base", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117909424.jpg", alt: "Backyard of a red brick ranch house with a new circle-pattern paver patio, stone step landing at the sliding glass door, and white vinyl privacy fence behind", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117912106.jpg", alt: "White vinyl privacy fence with a double gate and black hardware next to a red brick house with bare dirt and green lawn in the foreground", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117916824.jpg", alt: "White vinyl privacy fence enclosing a residential backyard with old stone edging along the base, bare lawn, and a utility pole visible behind", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117918892.jpg", alt: "Front of a gray painted brick house with new block retaining wall and integrated block steps from the sidewalk to the front door, metal handrail, lamp post, and mulch beds with shrubs", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117924700.jpg", alt: "Two-tier block retaining wall with integrated steps from the sidewalk up to the front door of a gray painted brick house, metal handrail, and straw-covered seed on both sides", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117927091.jpg", alt: "Long natural stone retaining wall in a residential backyard with straw-covered new seed on one side and bare dirt with plantings on the other, blue shed in the background", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117932817.jpg", alt: "Rough-cut natural stone retaining wall along a residential side yard next to a gray house with siding, straw-covered seed, cut tree stumps, and a wood pile behind", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117935257.jpg", alt: "Sunken paver patio with textured block retaining wall and integrated block steps, green hillside lawn above, and chain-link fence in the background", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117937621.jpg", alt: "Paver patio beneath a raised deck with gray painted stair railing, textured block retaining wall with integrated steps, and straw-covered seed on the hillside lawn", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117939915.jpg", alt: "Gray block paver patio with L-shaped block retaining wall, gravel drainage channel along the wall base, bare dirt yard awaiting seed, and wood privacy fence in the background", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117942181.jpg", alt: "Large gray paver patio in a backyard with a block seat wall on the left, bare dirt around the edges, wood privacy fence, storage shed, and residential neighborhood behind", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117944475.jpg", alt: "Two-tier textured block retaining wall with integrated block steps leading up a hillside next to a white house with siding, straw-covered seed on the ground, and wood privacy fence at the top", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117947310.jpg", alt: "Gray block retaining wall with a planter bed and a shrub, gravel drainage bed with a downspout extension, beneath a dark steel-post elevated deck structure in a wooded residential setting", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117950492.jpg", alt: "Gray block retaining wall supporting a concrete pad beneath a dark-stained elevated wood deck with stairs, wooded hillside with neighboring houses visible behind", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117954402.jpg", alt: "Tall gray block retaining wall built into a steep hillside below a dark modern house with a second-story balcony and cable railing, bare dirt slope, and a tree trunk in the foreground", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117973170.jpg", alt: "Long gray block retaining wall at street level with a weathered wood privacy fence and ornamental grasses on top, block steps on the left, and a residential neighborhood with mature trees", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117976247.jpg", alt: "Close-up of a long gray block retaining wall from street level with a weathered wood privacy fence and ornamental grasses on top, lawn in the foreground, and a residential street behind", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117978792.jpg", alt: "L-shaped gray block retaining wall with clay pots and plants on top, fresh poured concrete pad with a drain hole at the base, existing concrete driveway adjacent, in a residential neighborhood", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117984159.jpg", alt: "Long low block retaining wall with flat cap stones running along the side of a white house with siding, dry sandy yard on both sides, and a commercial brick building visible in the background", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117986736.jpg", alt: "Low block retaining wall with cap stones along the front of a white ranch house, teal dumpster in the driveway, dry yard, and a residential neighborhood", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117992796.jpg", alt: "Front yard of a residential home with freshly laid sod between concrete sidewalk sections, metal stair railings, brick porch column, and a residential street with houses in the background", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117995457.jpg", alt: "Gray block retaining wall with a metal handrail along a concrete sidewalk, freshly laid sod on both sides, and residential houses on a hillside behind", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117998376.jpg", alt: "Two-story white house with brick columns and a front porch, block retaining wall at sidewalk level with metal stair railings, and freshly laid sod lawn on a residential street", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118052551.jpg", alt: "Curved gray block retaining wall at the foundation of a new construction home wrapped in Tyvek house wrap, white river rock along the wall top, bare dirt hillside, and autumn trees in the background", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118055617.jpg", alt: "Two-tier dark charcoal block retaining wall at a new construction site with Tyvek house wrap visible, a skid-steer loader on the upper level, bare dirt grading, and an autumn sky", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118058135.jpg", alt: "Two-tier dark charcoal block retaining wall with light cap stones at a new construction site, Tyvek house wrap on the wall behind, a skid-steer on the hillside above, and bare dirt grading", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118064813.jpg", alt: "Curved gray block retaining wall with light cap stones wrapping around the foundation of a new construction home with Tyvek house wrap, white gravel drainage bed, and bare dirt lot", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118068830.jpg", alt: "Natural fieldstone and boulder retaining wall along the side of a house with white siding and a brick foundation, gravel drainage bed between the wall and house, and straw-covered seed on the yard", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118071402.jpg", alt: "Natural fieldstone and boulder retaining wall along the side of a house with white siding and brick foundation, gravel bed with a downspout, straw-covered seed, and a rural road in the background", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118075728.jpg", alt: "Lakefront residential property with a sand beach area bordered by large river rock, metal landscape edging, straw-covered new seed, and a pond with houses and a pedal boat visible across the water", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118078515.jpg", alt: "Close-up of brown paver steps with river rock on both sides and metal landscape edging, leading from a straw-covered lawn down to a sand beach area on a lakefront property", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118082191.jpg", alt: "Lakefront sand beach area bordered by large river rock viewed from the water's edge, with two-story houses with second-floor balconies behind and straw-covered new seed on the lawn", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118095618.jpg", alt: "Red-brown herringbone paver patio in a backyard with a horizontal wood slat privacy fence, river rock border along the edges, and shrubs behind the fence", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118098899.jpg", alt: "Red-brown herringbone paver patio beneath a raised deck with new wood stairs and railings, white downspout, gray soldier-course paver border, and a grass yard in the foreground", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118102866.jpg", alt: "Red-brown paver patio beneath a blue-sided two-story house with a horizontal wood slat privacy screen, river rock border with landscape edging, and straw-covered new seed on the surrounding yard", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118108795.jpg", alt: "Block retaining wall along a lakefront shoreline with paver steps in the foreground, sand beach area below, boat dock with canopy on the water, and straw-covered seed on the lawn above", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118113281.jpg", alt: "Tall pressure-treated lumber retaining wall built into a wooded hillside with a drainage pipe at the base, bare dirt grading below, and a basketball hoop visible at the top of the slope", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118116339.jpg", alt: "Low pressure-treated lumber retaining wall with a flat cap board running along an asphalt driveway edge in a wooded residential setting, bare dirt on the downhill side and plants along the base", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118118625.jpg", alt: "L-shaped pressure-treated lumber retaining wall at the corner of an asphalt driveway with fresh gravel fill on top, a dark-colored garage with a yellow door in the background, and mature trees surrounding the property", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118121674.jpg", alt: "Pressure-treated lumber retaining wall built into a wooded hillside with new boards on top of an older weathered wall below, bare dirt at the base, and mature trees with vines overhead", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118124488.jpg", alt: "Dark red-brown herringbone paver patio in a shaded backyard with a curved brown block retaining wall and block steps leading up to a yard with fence posts and a play structure behind", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118126734.jpg", alt: "Curved brown block retaining wall with cap stones and block steps viewed from above, herringbone paver patio below, fence posts and straw-covered seed on the upper yard, and a play structure in the background", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118129303.jpg", alt: "Block steps with paver treads and curved block retaining walls on both sides leading up from a herringbone paver patio to a grassy yard, with a wood pergola post and plants along the wall", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118131665.jpg", alt: "Herringbone paver patio in a backyard with a block planter wall containing trimmed shrubs, a block column with a flat cap, a weathered wood fence, and string lights in the background", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118133698.jpg", alt: "Wide view of a herringbone paver patio with a long block planter wall filled with trimmed shrubs, a soldier-course paver border, a weathered wood fence, and trees in the background", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118143218.jpg", alt: "Gray block retaining wall with flat cap stones along the front of a commercial building with a green sign pole, metal stair railings, concrete sidewalk, and a tree in the lawn area above", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118145981.jpg", alt: "Gray block retaining wall along the side of a commercial building with a metal stair railing at one end, green lawn on top, concrete sidewalk below, and a residential neighborhood across the street", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118148340.jpg", alt: "Gray block retaining wall with flat cap stones and a raised planter bed at the entrance of a commercial office building, metal stair railings, a business sign, concrete walkway, and parking lot", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118156243.jpg", alt: "Bernal Landscape Management branded trailer parked in a residential driveway with a manicured green lawn, river rock landscape beds with metal edging around a tree, and a house with stone accents", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118162715.jpg", alt: "Freshly mowed and striped green lawn at a multi-story apartment or condominium building with young trees, green metal sign posts, a concrete sidewalk, and a parking lot", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118165039.jpg", alt: "Freshly mowed and striped green lawn at a large multi-story apartment or condominium complex with mature trees, a mulch bed around a tree trunk, a curved concrete curb, and an asphalt drive", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118168178.jpg", alt: "Bernal crew member on a commercial zero-turn mower cutting striped lawn", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118172329.jpg", alt: "Curved brown block retaining wall with integrated block steps and a mulch planter bed at a residential property, Bernal Landscape trailer and a silver sedan parked on the street above, and mature trees", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118178618.jpg", alt: "Multi-tier brown block retaining wall with integrated block steps and a curved planter bed with mulch, Bernal Landscape trailer visible on the street above, and a concrete driveway below", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118190997.jpg", alt: "Long low block retaining wall with cap stones running through a backyard behind a gray-sided two-story house with a raised deck, bare dirt grading on both sides, and green lawn in the foreground", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118193448.jpg", alt: "Two-tier brown and gray block retaining wall on a rural residential property with a pole barn, basketball hoop, and open green fields behind, bare dirt grading in the foreground", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118197642.jpg", alt: "Block retaining wall with integrated block steps and river rock beds on both sides, leading up to a house with tan siding and a white staircase, an HVAC unit surrounded by river rock, and small plants along the steps", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118200512.jpg", alt: "Curved gray block retaining wall beneath a covered patio area with an HVAC unit and river rock fill on top, a crew member working in the background, and a wooded hillside with early spring trees", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118203175.jpg", alt: "Block retaining wall with paver steps and river rock beds on both sides leading up to a two-story house with tan siding and a white deck staircase, a crew member working near the foundation, and an HVAC unit", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118206273.jpg", alt: "Two-tier brown block retaining wall with river rock fill and small green plants along the foundation of a tan-sided house with a white deck staircase, bare dirt grading in the foreground", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118212238.jpg", alt: "Long tan block retaining wall with cap stones and a river rock strip running alongside a black aluminum pool fence, bare dirt on the uphill side, wooded hillside with early spring trees in the background", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118215014.jpg", alt: "L-shaped brown block retaining wall with white stone planter fill and small plants next to concrete steps with a metal handrail, a teal house and yellow house visible across the street in a residential neighborhood", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118218428.jpg", alt: "Stepped brown block retaining wall with white stone planter fill along the side of a gray-sided two-story house with a satellite dish, concrete sidewalk below, and residential homes across the street", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743118220886.jpg", alt: "Corner view of a tall brown block retaining wall with white stone planter fill at the top, black rocking chairs on the elevated porch above, concrete sidewalk and green lawn below in a residential neighborhood", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743853526770.jpg", alt: "Curved segmental block retaining wall with stairs and fresh sod lawn in a West Michigan backyard", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1771690330244.jpg", alt: "Natural stone retaining wall with built-in stone steps on a wooded slope", width: 960, height: 960 },
  { src: "/gallery/FB_IMG_1743117930153.jpg", alt: "Large stamped concrete patio with an irregular stone pattern behind a dark gray house with stone veneer accents, an Adirondack chair and metal patio furniture, a grill, and a wooded hillside behind", width: 921, height: 960 },
  { src: "/gallery/FB_IMG_1646188492026.jpg", alt: "Curved retaining wall with mulched planting beds, a flagstone patio, and a fire pit in a sloped backyard", width: 1080, height: 810 },
  { src: "/gallery/FB_IMG_1646188521681.jpg", alt: "Three Bernal plow trucks lined up at night with headlights on and plows lowered on a snowy lot", width: 1080, height: 810 },
  { src: "/gallery/FB_IMG_1743118285071.jpg", alt: "Dark charcoal textured block retaining wall with a drainage pipe opening built between concrete foundation walls and two outbuildings, large evergreen trees behind, and bare dirt in the foreground", width: 960, height: 813 },
  { src: "/gallery/FB_IMG_1576048889845.jpg", alt: "Expansive backyard lawn with crisp mowing stripes behind a gray two-story home", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1576048912848.jpg", alt: "Worker in a green articulated boom lift pruning the canopy of a tall tree", width: 720, height: 960 },
  { src: "/gallery/FB_IMG_1592501583860.jpg", alt: "Bernal Landscape Management branded Ford F-350 truck and enclosed trailer parked on a residential street", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1592501594710.jpg", alt: "Front entry of a brick home with mulch beds, spring daffodils, planters, and a concrete walkway", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1730473153055.jpg", alt: "Large block retaining wall with a flagstone patio and built-in fire pit on a sloped backyard with mulched beds", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1730473204705.jpg", alt: "Bernal Landscape Management branded truck and enclosed trailer with company logo and phone number", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1743117222558.jpg", alt: "Front yard mulching with Bernal Landscape trailer in the driveway and freshly applied wood chip mulch around a large tree", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1743117376572.jpg", alt: "Gray block retaining wall with integrated block steps and fresh topsoil behind it, running between two houses in a residential backyard, a basketball hoop and dark mulch bed visible at the top of the slope", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1743117632428.jpg", alt: "Large curved multi-tone paver patio with a concrete border extending beneath a second-floor deck of a cream-sided house, a natural boulder retaining wall with mulch on the far side, and a green lawn edge", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1743117790321.jpg", alt: "Paver patio surface with a built-in block fire pit in the foreground, block steps leading up to a retaining wall, bare dirt grading on the hillside above, and a wooded backdrop", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1743118000899.jpg", alt: "Two-tier curved gray-green block retaining wall with dark mulch fill and cap stones along the foundation of a green-sided house with a stone column porch, dark mulch groundcover below, and mature trees overhead", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1743118044067.jpg", alt: "Brown block retaining wall supporting a raised concrete slab patio behind a gray-sided house with a red door, trash bins in a wood-framed shelter, green lawn below, and crew members with equipment at the far end", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1743118048236.jpg", alt: "Curved tan block planter wall with wood chip mulch and evergreen trees planted inside, in front of a modern dark-sided house with stone veneer accents and large windows, gravel ground surrounding the planter", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1743118257979.jpg", alt: "Multi-tone paver patio with a walkway extension bordered by black landscape sheeting weighted with solar lights, a chain-link fence and green lawn in the background, dappled shade from overhead trees", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1743118260303.jpg", alt: "Gray block steps with flat paver treads leading up from a sand beach area to a grassy yard with straw-covered new seed, block retaining wall wing walls on both sides", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1743118263296.jpg", alt: "Block retaining wall with cap stones and block steps along a lakefront shoreline, a sand beach area below, a yellow two-story house and neighboring homes on the grassy slope above, and a boat dock on the water", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1743118266569.jpg", alt: "Wide view of a lakefront block retaining wall curving along the shoreline with block steps, a sand beach area, straw-covered seed on the lawn, two houses and a play structure visible, and a boat dock on the water", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1743118269213.jpg", alt: "Dark charcoal textured block retaining wall with a drain pipe opening built between concrete foundation walls and outbuildings, large evergreen trees behind, bare dirt and debris in the foreground", width: 720, height: 960 },
  { src: "/gallery/FB_IMG_1743118271392.jpg", alt: "Gray block retaining wall with cap stones and block steps running along a narrow concrete walkway between a new cedar fence and a raised garden bed with hostas and plants, mature trees overhead", width: 720, height: 960 },
  { src: "/gallery/FB_IMG_1743118273591.jpg", alt: "Gray block retaining wall with cap stones along a narrow walkway between a cedar fence and a raised planting bed, view through a fence opening showing flowering plants and an evergreen tree, gravel drainage strip along the base", width: 720, height: 960 },
  { src: "/gallery/FB_IMG_1743118278713.jpg", alt: "Concrete walkway with a gray block retaining wall and cap steps on one side and planting beds on both sides featuring hostas, red flowers, and green shrubs, block steps leading up to a cedar fence in the background", width: 720, height: 960 },
  { src: "/gallery/FB_IMG_1743118287757.jpg", alt: "Gray block retaining wall with cap stones along the side of a tan-sided house with gravel fill behind the wall, a window well visible, and mature trees including a weeping evergreen overhead, river rock along the base", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1743118290326.jpg", alt: "New pressure-treated wood privacy fence running along a residential property line with freshly graded dark topsoil in the foreground, a red-sided house and gray house visible beyond the fence, mature trees overhead", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1743118292529.jpg", alt: "Backyard with a new cedar privacy fence, a river rock slope with wood stairs and a wood handrail leading up to a gate in the fence, bare dirt grading in the foreground, and large trees overhead", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1743118294742.jpg", alt: "Block steps with paver treads and wood post-and-rail handrails on both sides leading up through a river rock slope to a cedar privacy fence with an arched gate at the top, mature trees overhead", width: 720, height: 960 },
  { src: "/gallery/FB_IMG_1743118302538.jpg", alt: "Rectangular gray paver patio with two dark wicker chairs with red cushions and a small side table, bordered by dark mulch beds and natural boulders, surrounded by tall pine trees with dappled sunlight", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1743118306253.jpg", alt: "Curved gray block retaining wall with cap stones under construction behind a brown-sided house with a wood deck, bare sand fill inside the wall, green lawn and a trampoline in the background", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1743118330227.jpg", alt: "Short gray block retaining wall with cap stones and a black lamppost along a curved asphalt driveway, dark mulch bed with rounded green shrubs and purple flowers, natural stone steps at the corner, brick house partially visible", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1743118332803.jpg", alt: "Gray block retaining wall with cap stones along a curved asphalt driveway viewed from stone steps, rounded green and gold shrubs in the mulch bed, brick paver walkway on the left, mature trees in the background", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1743118337954.jpg", alt: "Long gray block retaining wall with cap stones along a curved asphalt driveway leading to a tan brick ranch-style home with manicured green shrubs, a red-leafed tree, and tall pine trees in the background", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1743118345855.jpg", alt: "Tan block retaining wall with cap stones running along a wooded hillside, freshly graded bare dirt and sparse grass below, leaf litter and trees on the slope above, a sprinkler head visible at the base", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1743118348486.jpg", alt: "Dark charcoal block retaining wall with cap stones running along a concrete driveway next to a white-sided house, chain-link fence on top, green lawn behind the wall, a blue house and garages visible across the yard", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1743118350996.jpg", alt: "L-shaped dark charcoal block retaining wall with cap stones along a concrete driveway, chain-link fence on top, white-sided house with a teal umbrella and lawn chairs in the backyard, a brick house visible across the yard", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1743118353309.jpg", alt: "Curved dark charcoal block retaining wall with integrated block steps and cap stones next to a concrete driveway, chain-link fence on top, green lawn behind, a white house and trees in the background", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1743118360498.jpg", alt: "Tan block retaining wall with cap stones surrounding a covered in-ground pool with a blue winter cover, block steps on both sides, green groundcover and a dark wood fence in the background, mature trees overhead", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1743118362593.jpg", alt: "Tan block retaining wall with cap stones and steps along a concrete pool deck next to an in-ground pool with a blue cover, green groundcover plants climbing behind, dark wood fence and mature trees in the background", width: 720, height: 960 },
  { src: "/gallery/FB_IMG_1743118364329.jpg", alt: "Paver walkway leading to a tan block retaining wall with block steps beside an in-ground pool with a blue cover and roller, green groundcover and dark wood fence behind, wooded hillside in the background", width: 720, height: 960 },
  { src: "/gallery/FB_IMG_1743118369654.jpg", alt: "Tan block planter wall with cap stones and green groundcover growing inside, next to a concrete pool deck with a black metal post, a dark wood fence and brick house behind, a linear drain channel along the base", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1743118372237.jpg", alt: "Tan block retaining wall with cap stones and block steps along a concrete pool deck, green groundcover on the hillside above, dark wood fence and metal railing, blue pool cover edge visible, wooded backdrop", width: 720, height: 960 },
  { src: "/gallery/FB_IMG_1743118374825.jpg", alt: "Tan block retaining wall with cap stones and wide block steps next to a concrete pool deck, green groundcover on the upper slope, a blue lounge chair leaning against a brick house, dark wood fence and spiral staircase visible", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1743118425609.jpg", alt: "Curved natural stone retaining wall with paver walkway and planter beds on a sloped backyard behind a dark brown-sided house with a second-floor balcony, dormant shrubs and bare soil, pine trees in the background", width: 720, height: 960 },
  { src: "/gallery/FB_IMG_1743118427946.jpg", alt: "Large tan block retaining wall with block steps supporting a covered patio beneath a dark gray two-story house with white columns, green climbing vine on a conical evergreen, natural boulder accents, bare graded soil in the foreground", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1743118430585.jpg", alt: "Multi-tier tan block retaining wall with block steps on a sloped lot behind a dark gray two-story house, planter bed between wall tiers, bare graded soil in the foreground, additional retaining walls and a play structure visible uphill", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1743118437473.jpg", alt: "Gray block retaining wall with cap stones curving along a lakefront shoreline, a blue-sided house with white deck stairs on the green lawn above, tall ornamental grasses, straw-covered new seed on the slope, boats and docks on the water", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1743118440541.jpg", alt: "Long gray block retaining wall with cap stones along a lakefront channel, multiple two-story houses with green lawns on the slope above, a pontoon boat docked on the left, a natural boulder wall visible on a neighboring property", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1743118451987.jpg", alt: "Multi-tier dark charcoal block retaining wall with two sets of block steps on a steep slope between two houses, straw-covered new seed on the hillside, a lamppost and white deck railing at the top, blue sky overhead", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1743118454586.jpg", alt: "Side view of a multi-tier dark charcoal block retaining wall with winding block steps on a steep slope next to a gray-sided house, straw-covered new seed on the hillside, a lamppost and houses visible at the top", width: 720, height: 960 },
  { src: "/gallery/FB_IMG_1743118480015.jpg", alt: "Gray block retaining wall with cap stones curving along a lakefront pond, a Bernal Landscape Management yard sign on the green lawn, a tan two-story house with a wood staircase and balcony above, neighboring homes across the water", width: 720, height: 960 },
  { src: "/gallery/FB_IMG_1743118507560.jpg", alt: "Decorative kidney-shaped block planter with two tiers of tan block walls, dark mulch and colorful flowering plants inside, a Bernal Landscape Management yard sign, green lawn surrounding, a residential street and brown building in the background", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1743118510032.jpg", alt: "Gray paver patio surface along a tan block retaining wall next to a brick house, an air conditioning unit and bags of material on the left, river rock drainage strip between the wall and a narrow walkway, potted flowers on the wall cap", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1743118515920.jpg", alt: "Lakefront property with tan block retaining walls and a round block fire pit on a sand beach area, a brown brick house with wood stairs and a screened porch on the left, a yellow house with an American flag on the right, water in the foreground", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1743118527499.jpg", alt: "Gray block retaining wall with cap stones and center block steps on a lakefront beach, sand in the foreground, bare dirt grading above the wall, a dark-sided A-frame house with a covered porch and Adirondack chairs on the lawn behind, dusk lighting", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1743118570235.jpg", alt: "After photo of a terraced gray block retaining wall with block steps and a round stone fire pit on a leveled area next to a white vinyl pool fence, a white shed and green hillside in the background, bare dirt grading in progress", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1771690046733.jpg", alt: "Lakefront tan block retaining walls and a round block fire pit on a sand beach viewed from the water, a brown brick house with wood stairs on the left and a yellow house with an American flag on the right, green lawns sloping to the shoreline", width: 960, height: 720 },
  { src: "/gallery/FB_IMG_1771690000910.jpg", alt: "Pressure-treated timber retaining walls with stepped terraces running along a wooded hillside next to a tan-sided house, bare dirt between the walls, dappled sunlight through mature trees overhead", width: 675, height: 900 },
  { src: "/gallery/FB_IMG_1743118486612.jpg", alt: "Crew members building a curved gray block retaining wall with block steps next to a white-sided house, an air conditioning unit at the base, a worker in a safety vest on the upper level, bare dirt grading in the foreground", width: 921, height: 640 },
  { src: "/gallery/FB_IMG_1576039719330.jpg", alt: "Bernal Landscapes branded truck towing an enclosed trailer with company logo on a residential street", width: 960, height: 540 },
  { src: "/gallery/FB_IMG_1576048925240.jpg", alt: "Crew member operating a New Holland skid steer clearing brush and branches on a job site", width: 540, height: 960 },
  { src: "/gallery/FB_IMG_1743118460450.jpg", alt: "Tan block retaining wall with cap stones and block steps surrounding a curved in-ground pool with blue water, a concrete pool deck, ornamental grasses and shrubs in the planter beds above, a stucco house with a second-floor balcony", width: 945, height: 480 },
  { src: "/gallery/FB_IMG_1583161379617.jpg", alt: "Bernal Landscape truck and branded trailer with a crew member mowing on a commercial mower in the background", width: 810, height: 457 },
  { src: "/gallery/FB_IMG_1743118564100.jpg", alt: "Before photo of a sloped backyard with a small block fire pit, a black bench, and a white vinyl pool fence with a pool slide visible behind it, a white shed and green hillside in the background, bare late-fall lawn", width: 640, height: 466 },
];

// Featured photos curated for hero/section use elsewhere on the site.
export const FEATURED = {
  hero: "/gallery/FB_IMG_1771944411767.jpg",
  about: "/gallery/20250411_172601.jpg",
  servicesIndex: "/gallery/20250411_172615.jpg",
  gallery: "/gallery/20250411_172838.jpg",
  contact: "/gallery/20250411_172928.jpg",
  reviews: "/gallery/FB_IMG_1754343308690.jpg",
  serviceAreas: "/gallery/FB_IMG_1754343316006.jpg",
} as const;

// A small set of "best" highlight photos for use on the home page.
export const HOME_HIGHLIGHTS: GalleryImage[] = [
  { src: "/gallery/20250411_172500.jpg", alt: "Paver-edged mailbox bed filled with white gravel in a West Michigan residential neighborhood", width: 4000, height: 3000 },
  { src: "/gallery/20250411_172601.jpg", alt: "Oval paver-edged front yard bed with white rock, ornamental tree, and boulder accent beside a white house", width: 4000, height: 3000 },
  { src: "/gallery/20250411_172615.jpg", alt: "Curved paver-edged landscape bed with white gravel, a young tree, boulder accent, and shrubs along a house", width: 4000, height: 3000 },
  { src: "/gallery/20250411_172838.jpg", alt: "Paver-edged landscape bed with white gravel, dormant shrubs, and decorative pots along the front of a house", width: 4000, height: 3000 },
  { src: "/gallery/20250411_172928.jpg", alt: "Circular paver-edged tree ring filled with white gravel and a boulder accent around a young tree in a front yard", width: 4000, height: 3000 },
  { src: "/gallery/FB_IMG_1754343308690.jpg", alt: "Low paver-capped retaining wall along the side of a brick house with gravel drainage channel, mulch bed, and newly seeded lawn", width: 1440, height: 1440 },
  { src: "/gallery/FB_IMG_1754343316006.jpg", alt: "Block retaining wall with gravel drainage channel between the wall and a brick house foundation with gas meter visible", width: 1440, height: 1440 },
  { src: "/gallery/FB_IMG_1758729997354.jpg", alt: "Fresh sod installed in a backyard with horizontal-board wood fence and deck", width: 1440, height: 1440 },
  { src: "/gallery/FB_IMG_1758730003165.jpg", alt: "Freshly installed sod in a side yard with a horizontal cedar fence with black metal posts and a wood deck", width: 1440, height: 1440 },
];

// Bigger "featured" set for showcase grids (about, services index, etc.).
export const FEATURED_GRID: GalleryImage[] = GALLERY.slice(0, 24);

/**
 * Deterministically pick N photos from the gallery for a given key (e.g. a
 * service slug). The same key always returns the same slice, so the per-
 * service "Recent Work" section stays consistent between renders.
 */
export function pickGallery(seed: string, count = 8): GalleryImage[] {
  let hash = 0;
  for (let i = 0; i < seed.length; i++) hash = (hash * 31 + seed.charCodeAt(i)) >>> 0;
  const start = hash % Math.max(1, GALLERY.length - count);
  return GALLERY.slice(start, start + count);
}

export const TESTIMONIALS = [
  {
    name: "Dawn L.",
    quote:
      "Stayed on time and in budget, did quality work, and used quality materials. Very professional. Will use them again when we need more landscape retaining walls.",
  },
  {
    name: "Jamal A.",
    quote:
      "Bernal Landscaping did a great job on my lawn last summer. They also kept my sidewalks and driveways clear whenever it snowed. I'll never use another landscaping company again — they exceeded all my expectations.",
  },
  {
    name: "Dante M.",
    quote:
      "Very professional, great communication, and always willing to do the work as expected. Will be doing business in the upcoming season. Thank you for the good work.",
  },
  {
    name: "Ethan W.",
    quote:
      "We used this service for landscaping in our yard. We had new gardens cut out and river rock and mulch spread. They did an awesome job. I highly recommend this company.",
  },
] as const;
